// <auto-generated>
//     此文件为自动生成文件，请勿手改，重新绑定会覆盖。
// </auto-generated>

using Framework.Core;
using Framework.Panel;
using UnityEngine.UI;

namespace UI.MainScene
{
    /// <summary>
    /// MainScenePanel 的控件绑定
    /// </summary>
    public partial class MainScenePanel : PanelController, UIView.IBindable
    {
        private Button _hostPlayBtn;
        private Button _localPlayBtn;
        private Button _multiPlayBtn;
        private Button _settings;

        /// <summary>
        /// 由 UIView 在挂载后调用，写入预制体上绑定的控件
        /// </summary>
        public void Bind(UIView view)
        {
            _hostPlayBtn = (Button)view.GetBinding("hostPlayBtn");
            _localPlayBtn = (Button)view.GetBinding("localPlayBtn");
            _multiPlayBtn = (Button)view.GetBinding("multiPlayBtn");
            _settings = (Button)view.GetBinding("settings");
        }
    }
}
