// ========================================
// 基础连接协议，用于搭建客户端与服务端通信基础
// 不应在此添加业务协议
// ========================================
syntax = "proto3";

package NetConnect;

message Client_Reliable_Connect_Request {
  // 初次连接全为0，重连时带上旧信息
  uint32 client_id = 1;
  uint64 token = 2;
}

message Client_Reliable_Connect_Response {
  uint32 client_id = 1;
  uint64 token = 2;
  int32 fast_port = 3;
}

message Client_Fast_Connect_Request {
  uint32 client_id = 1;
  uint64 token = 2;
}

message Heart_Beat_Request {
  // 待定
}

message Heart_Beat_Response {
  // 待定
}

message Ping {
  int64 timestamp = 1;
}

message Pong {
  int64 timestamp = 1;
}

message Chat_Test {
  string content = 1;
}

