syntax = "proto3";

package NetSync;

message Vec2 {
  float x = 1;
  float y = 2;
}

message Vec3 {
  float x = 1;
  float y = 2;
  float z = 3;
}

// 玩家输入命令
// TODO: 先保证最小同步原型，只同步位置和旋转
message Player_Input {
  uint32 clientId = 2;
  uint32 inputTick = 3;
  Vec2 move_input = 4;
  Vec2 aim_input = 5;
}

// 玩家状态快照
message Player_Snapshot {
  uint32 clientId = 2;
  uint32 snapshotTick = 3;
  uint32 lastProcessedInputTick = 4;
  Vec3 position = 5;
  Vec3 rotation = 6;
}

message World_Snapshot {
  uint32 snapshotTick = 1;
  repeated Player_Snapshot player_snapshots = 2;
}

// ========== 加入游戏 ==========
message Game_Join_Request {
  uint32 clientId = 1;
}

message Game_Join_Response {
  bool accepted = 1;
}
// ========== 加入游戏 ==========