syntax = "proto3";

package NetSync;

message Vec2 {
  float x = 1;
  float y = 2;
}

message Vec3 {
  float x = 1;
  float y = 2;
  float z = 3;
}

message Quat {
  float x = 1;
  float y = 2;
  float z = 3;
  float w = 4;
}

// ========== 房间管理 ==========
message Room_Join_Request {
}

message Room_Join_Response {
  bool accepted = 1;    // 是否接收加入请求
  uint32 playerId = 2;  // 分配的玩家ID
  uint32 hostPlayerId = 3;  // 主机玩家ID
  repeated uint32 playerIds = 4;  // 所有玩家ID
}

// 通知新的玩家加入房间
message Room_Player_Joined_Notify {
  uint32 playerId = 1;  // 分配的玩家ID
}

message Room_Leave_Request {
}

// 玩家退出通知
message Room_Player_Leave_Notify {
  uint32 playerId = 1;
}

// 房主退出，房间销毁通知
message Room_Host_Dissolved_Notify{
}
// ========== 房间管理 ==========

// ========== 状态同步 ==========
// 本机玩家输入。玩家由发送这条消息的连接决定。
message Player_Input {
    uint32 inputTick = 1;
    Vec2 move_input = 2;
    Vec2 aim_input = 3;
    bool is_primary_attack_pressed = 4;
    bool is_special_attack_pressed = 5;
    bool is_special_action_pressed = 6;
    bool is_interact_pressed = 7;
    bool is_sprint_pressed = 8;
    bool is_jump_pressed = 9;
    bool is_switch_mode_pressed = 10;
}

// 玩家实体在某一Tick的状态
message Player_Snapshot {
    uint32 entityId = 1;
    uint32 locomotion_state = 2;
    Vec3 position = 3;
    Quat rotation = 4;
    Quat view_rotation = 5;
    Vec3 linear_velocity = 6;
    Vec3 angular_velocity = 7;
    uint32 lastProcessedInputTick = 8;
}

message World_Snapshot {
    uint32 snapshotTick = 1;
    repeated Player_Snapshot Player_snapshots = 2;
}
// ========== 状态同步 ==========

// ========== 实体生成 ==========
// 主机通知客户端生成实体
message Entity_Spawn_Notify {
  uint32 entityId = 1;
  uint32 entityTypeId = 2;
  uint32 playerId = 3;
  Vec3 position = 4;
  Quat rotation = 5;
}

// 主机通知客户端销毁实体
message Entity_Destroy_Notify {
  uint32 entityId = 1;
}

// 客户端关卡就绪后，向主机请求已有实体
message Entity_Spawn_Sync_Request {
}
// ========== 实体生成 ==========
